SCAcademy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from project import urls as projects_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(projects_urls))
]

project/urls.py
from django.conf.urls import url
from project import views

app_name = 'project'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/StudentsClubAcademy
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    #/StudentsClubAcademy

    url(r'^subject/$', views.SubjectView.as_view(), name='subject'),
    #/StudentsClubAcademy/Subject/

    url(r'^subject/(?P<subject_id>[0-9]+)/$', views.ShowSubjectView.as_view(), name='show_subject'),
    #/StudentsClubAcademy/Subject/1/


    url(r'^subject/(?P<subject_id>[0-9]+)/cource/$', views.CourceView.as_view(), name='cource'),
    #/StudentsClubAcademy/Subject/1/Cource/

    url(r'^subject/(?P<subject_id>[0-9]+)/cource/(?P<cource_id>[0-9]+)/$', views.ShowCourceView.as_view(), name='show_cource'),
    #/StudentsClubAcademy/Subject/1/Cource/1/

    url(r'^cource/add/$', views.CourceCreate.as_view(), name='add-cource'),
    #/StudentsClubAcademy/Subject/1/Cource/add/
    url(r'^subject/(?P<subject_id>[0-9]+)/cource/(?P<cource_id>[0-9]+)/update/$', views.CourceUpdate.as_view(), name='update-cource'),
    #/StudentsClubAcademy/Subject/1/Cource/2/update/
    url(r'^subject/(?P<subject_id>[0-9]+)/cource/(?P<cource_id>[0-9]+)/delete/$', views.CourceDelete.as_view(), name='delete-cource'),
    #/StudentsClubAcademy/Subject/1/Cource/2/delete


    url(r'^cource/(?P<cource_id>[0-9]+)/lecture/(?P<lecture_id>[0-9]+)/$', views.ShowLectureView.as_view(), name='show_lecture'),
    #/StudentsClubAcademy/Cource/2/Lecture/1/

    url(r'^lecture/add/$', views.LectureCreate.as_view(), name='add-lecture'),
    #/StudentsClubAcademy/Subject/1/Cource/2/Lecture/add/
    url(r'^subject/(?P<subject_id>[0-9]+)/cource/(?P<cource_id>[0-9]+)/lecture/(?P<lecture_id>[0-9]+)/update/$', views.LectureUpdate.as_view(), name='update-lecture'),
    #/StudentsClubAcademy/Subject/1/Cource/2/Lecture/2/
    url(r'^subject/(?P<subject_id>[0-9]+)/cource/(?P<cource_id>[0-9]+)/lecture/(?P<lecture_id>[0-9]+)/delete/$', views.LectureDelete.as_view(), name='delete-lecture'),
    #/StudentsClubAcademy/Subject/1/Cource/2/Lecture/2/delete

    url(r'^commentforlecture/add/$', views.LectureComment.as_view(), name='add-comment-l'),
    #/StudentsClubAcademy/commentforlecture/add/
    url(r'^lecture/(?P<lecture_id>\d+)/comment/$', views.comment_l, name='l_comment'),
    #/StudentsClubAcademy/Lecture/1/comment/

    url(r'^commentforcource/add/$', views.CourceComment.as_view(), name='add-comment-c'),
    #/StudentsClubAcademy/commentforcource/add/
    url(r'^cource/(?P<cource_id>\d+)/comment/$', views.comment_c, name='c_comment'),
    #/StudentsClubAcademy/cource/1/comment/

]

project/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

class Subject(models.Model):
    name = models.CharField(max_length=100)
    collage = models.CharField(max_length=100)
    level = models.CharField(max_length=7)
    def get_absolute_url(self):
        return reverse('project:cource', kwargs={'pk':self.pk})
    def __unicode__(self):
        return self.name + '-' + self.collage

class Cource(models.Model):
    subject = models.ForeignKey(Subject)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    pup_date = models.DateTimeField(auto_now_add=True)
    location = models.TextField(max_length=1000)

    def __unicode__(self):
        return self.title

class Lecture(models.Model):
    cource = models.ForeignKey(Cource, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    sources = models.TextField(max_length=500)
    objectives = models.TextField(max_length=500)
    pup_date = models.DateTimeField(auto_now_add=True)
    link = models.URLField()
    def __unicode__(self):
        return self.title

class Comment_c (models.Model):
    cource = models.ForeignKey(Cource, on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    body = models.TextField()
    pup_date = models.DateTimeField(auto_now_add=True)

class Comment_l (models.Model):
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    body = models.TextField()
    pup_date = models.DateTimeField(auto_now_add=True)

project/forms.py
from django.contrib.auth.models import User
from django import forms

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

project/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.views import generic
from project.models import Subject, Cource, Lecture, Comment_l, Comment_c
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from .forms import Userform
from django.http import HttpResponseRedirect

class UserFormView(View):
    form_class = Userform
    template_name= 'project/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user= form.save(commit=False)

            username = form.clean_data['username']
            password = form.clean_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('project:index')
        return render(request, self.template_name, {'form':form})

class IndexView(generic.ListView):
    template_name = 'project/index.html'
    context_object_name = 'all_subjects'
    def get_queryset(self):
        return Subject.objects.all()

class SubjectView(generic.ListView):
    template_name = 'project/subject.html'
    context_object_name = "Subject"
    def get_queryset(self):
        return Cource.objects.all()

class ShowSubjectView(generic.DetailView):
    model = Subject
    template_name = 'project/subject.html'
    context_object_name = "Subject"
    pk_url_kwarg = "subject_id"
    query_pk_and_slug = True

class CourceView(generic.ListView):
    template_name = 'project/cource.html'
    context_object_name = "Cource"
    def get_queryset(self):
        return Lecture.objects.all()

class ShowCourceView(generic.DetailView):
    model = Cource
    template_name = 'project/cource.html'
    context_object_name = "Cource"
    pk_url_kwarg = "cource_id"
    query_pk_and_slug = True

class ShowLectureView(generic.DetailView):
    model = Lecture
    template_name = 'project/show_lecture.html'
    context_object_name = "Lecture"
    pk_url_kwarg = "lecture_id"
    query_pk_and_slug = True



class CourceCreate(CreateView):
    model = Cource
    fields = ['subject','title', 'description', 'location' ]
    success_url = reverse_lazy('project:index')
    pk_url_kwarg = "cource_id"
    query_pk_and_slug = True
class CourceUpdate(UpdateView):
    model = Cource
    fields = ['subject','title', 'description', 'location' ]
    success_url = reverse_lazy('project:index')
    pk_url_kwarg = "cource_id"
    query_pk_and_slug = True
class CourceDelete(DeleteView):
    model = Cource
    success_url = reverse_lazy('project:index')
    pk_url_kwarg = "cource_id"
    query_pk_and_slug = True

class LectureCreate(CreateView):
    model = Lecture
    fields = ['cource','title', 'sources','objectives', 'link' ]
    success_url = reverse_lazy('project:index')
    pk_url_kwarg = "lecture_id"
    query_pk_and_slug = True
class LectureUpdate(UpdateView):
    model = Lecture
    fields = ['cource','title', 'sources','objectives', 'link' ]
    success_url = reverse_lazy('project:index')
    pk_url_kwarg = "lecture_id"
    query_pk_and_slug = True
class LectureDelete(DeleteView):
    model = Lecture
    success_url = reverse_lazy('project:index')
    pk_url_kwarg = "lecture_id"
    query_pk_and_slug = True


class CourceComment(CreateView):
    model = Comment_c
    fields = ['cource','author', 'body' ]
    success_url = reverse_lazy('project:index')
    context_object_name = "Cource"
    pk_url_kwarg = "cource_id"
    query_pk_and_slug = True

def comment_c(request, cource_id):
    cource= get_object_or_404(Cource, id=cource_id)
    cource.comment_l_set.all()
    user_comment=request.POST['comment']
    author = request.POST['author']
    comment_c.objects.create(
        cource=cource,
        author=author,
        body=user_comment,
    )
    return HttpResponseRedirect(reverse('show_cource', args=(cource_id)))


class LectureComment(CreateView):
    model = Comment_l
    fields = ['lecture','author', 'body' ]
    success_url = reverse_lazy('project:index')
    context_object_name = "Lecture"
    pk_url_kwarg = "lecture_id"
    query_pk_and_slug = True


def comment_l(request, lecture_id):
    lecture= get_object_or_404(Lecture, id=lecture_id)
    lecture.comment_l_set.all()
    user_comment=request.POST['comment']
    author = request.POST['author']
    comment_l.objects.create(
        lecture=lecture,
        author=author,
        body=user_comment,
    )
    return HttpResponseRedirect(reverse('ShowLectureView', args=(lecture_id)))

project/templates/project/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} Students Club Academy {% endblock %} </title>
    <link rel="icon" href="https://yt3.ggpht.com/-KMyUX0GJNlo/AAAAAAAAAAI/AAAAAAAAAAA/MUVpsW7Z_uc/s900-c-k-no-mo-rj-c0xffffff/photo.jpg">
    <!-- Loads the path to your static files-->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}" />

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Font Awesome glyphicons ç -->
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
/* Body */
body{color: white; font-family:'Proxima Nova','Helvetica','Corbel',sans-serif;}
.background{background-color:#4b5462; opacity: 0.7; }

/* Lists */
ul {display:inline-block;background-color:#4b5462;padding:10px;}
li {display:inline-block;color:white;background-color:#4b5462;padding:10px;}
li:hover {color: #56d0b3 }

/* Links */
a:link {color:white;background-color: transparent;text-decoration: none;}
a:visited {color:white;background-color: transparent;text-decoration: none;}
a:hover {color: rgb(80, 193, 167);background-color: transparent;text-decoration: none;}
a:active {color: rgb(80, 193, 167);background-color: transparent;text-decoration: underline;}
a:link#h1 {color:white;background-color: transparent;text-decoration: none;}
a:visited#h1 {color:white;background-color: transparent;text-decoration: none;}
a:hover#h1 {color:#4b5462;background-color: transparent;text-decoration: none;}
a:active#h1 {color: #4b5462;background-color: transparent;text-decoration: none;}
a:hover#t {color:blue; background-color: transparent;text-decoration: none;}
a:hover#f {color:blue; background-color: transparent;text-decoration: none;}
a:hover#w {color:black; background-color: transparent;text-decoration: none;}

/* Forms */
input[type=text] {font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;color: white;width: 300px;box-sizing: border-box;border: 2px solid white;font-size: 16px;background-color: #4b5462;outline: none;opacity: 0.3;}
input[type=text]:focus {font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;color: white;width: 300px;box-sizing: border-box;border: 2px solid white;font-size: 16px;background-color: #4b5462;outline: none;opacity: 0.7;}
input[type=email] {font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;color: white;width: 300px;box-sizing: border-box;border: 2px solid white;font-size: 16px;background-color: #4b5462;outline: none;opacity: 0.3;}
input[type=email]:focus {font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;color: white;width: 300px;box-sizing: border-box;border: 2px solid white;font-size: 16px;background-color: #4b5462;outline: none;opacity: 0.7;}
input[type=Send]{width:30px;height:10px;background-color: #4b5462;border: none;color: white;padding: 15px 15px;text-decoration: none;cursor: pointer;}
input[type=Send]:hover{width:30px;height:10px;background-color: #4b5462;border: none;color: white;padding: 15px 15px;text-decoration: underline;cursor: pointer;}
textarea{background-color: #4b5462;}
select {border: none;border-radius: 4px;background-color: #4b5462;outline: none}

/* Video Background */
.video-bg{position: fixed;z-index: -1000;width:100%;height:100%;overflow: hidden;top:0;left:0;}
#video-bg-elem{position: absolute;min-width:100%;min-height:100%;top:0;left:0;}
</style>

</head>
<body>

<!-- Video Background -->
<div class="video-bg">
<video id="video-bg-elem" preload autoplay loop="loop">
<source src="https://cdn.kastatic.org/videos/homepage-background.mp4" type="video/mp4" >
<source src="https://cdn.kastatic.org/videos/homepage-background.webm" type="video/webm" >
<source src="https://cdn.kastatic.org/videos/homepage-background.ogv" type="video/ogv" >
</video>
</div>

<!-- Website Content -->
<div class="content">
<div class="container">
<br/>
<p style="font-size: 50px;line-height: 2px;font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;font-weight: lighter"><img src="https://yt3.ggpht.com/-KMyUX0GJNlo/AAAAAAAAAAI/AAAAAAAAAAA/MUVpsW7Z_uc/s900-c-k-no-mo-rj-c0xffffff/photo.jpg" alt="Logo" style="width:90px;height:60px;"> <a href="{% url 'project:index' %}" target="_blank" id="h1"> <b>Students Club</b> Academy </a><p>

<!-- Navbar -->
<div class="row">
    <div class="col-sm-11 background">
    <div class="container-fluid">
    <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
    <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'project:index' %}"> <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Subject </a>
                </li>
                <li>
                    <a href="{% url 'project:add-cource' %}"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Cource </a>
                </li>
                <li>
                    <a href="{% url 'project:add-lecture' %}"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Lecture </a>
                </li>
                <li>
                    {% block add %} <a href="{% url 'project:register' %}"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Register </a> {% endblock %}
                </li>
            </ul>
        </div>
    </div>
    </div>
</div>
<!-- Content -->
<div class="row">
    <div class="col-sm-11 background">
        <div class="panel-group" id="accordion" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">

            {% block body %}
            {% endblock %}
    <div class="col-sm-4 background">
        <h3> Contact us: </h3>
            <form>
            SOCIAL:&nbsp;
            &nbsp;<a href= "https://twitter.com/Studentsofksauh" target="_blank"><i class="fa fa-twitter" aria-hidden="true" ></i></a>
            &nbsp;&nbsp;<a href= "https://www.enjazportal.com/" target="_blank"><i class="fa fa-rss" aria-hidden="true"></i></a><br/>
        </form>
        <br/>
    </div>
        </div>
</div>

<!-- Colom 2 Contact SCAcademy -->

</div>
</div>
</div>

<!-- Please work -->

</body>
</html>

project/templates/project/comment_c_form.html
{% extends 'project/base.html' %}
{% block title %} Comment {% endblock %}
{% block body %}

<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Comment </a></h3>
    </div>
        <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'project/form-template.html' %}
            <div class="form-group" action="{% url 'project:add-comment-c'%}">
                <div class="col-sm-offset-2 col-sm-10">

                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>

{% endblock %}

project/templates/project/comment_l_form.html
{% extends 'project/base.html' %}
{% block title %} Comment {% endblock %}
{% block body %}

<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Comment</a></h3>
    </div>
        <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'project/form-template.html' %}
                <div class="form-group" action="{% url 'project:add-comment-l' %}">
                    <div class="col-sm-offset-2 col-sm-10">

                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

project/templates/project/cource.html
{% extends 'project/base.html' %}
{% block title %} {{ Cource.title }} {% endblock %}
{% block add %} <a href="{% url 'project:add-comment-c' %}"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Comment </a> {% endblock %}

{% block body %}


<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1"> <span class="glyphicon glyphicon-book" aria-hidden="true"></span> {{ Cource.title }} </a></h3>
    </div>
        <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
            <h6>{{ Cource.pup_date }}</h6>
            <h4> Course Location: {{ Cource.location }}</h4>
            <h4> Description: {{ Cource.description }}</h4>
        </div>
    </div>
</div>

<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title" ><a data-toggle="collapse" data-parent="#accordion" href="#collapse2"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> Lectures </a></h3>
    </div>
    <div id="collapse2" class="panel-collapse collapse" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <div class="panel-body" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
            {% if Cource.lecture_set.all %}
                <ul>
                {% for Lecture in Cource.lecture_set.all %}
                    <li><a href="{% url 'project:show_lecture' Cource.pk Lecture.pk %}"> {{ Lecture.title }} </a> ({{ Lecture.pup_date }}) </li></br>
                {% endfor %}
                </ul>
            {% else %}
                <p> No lectures are available yet. </p>
            {% endif %}



        </div>
    </div>
</div>

<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title" ><a data-toggle="collapse" data-parent="#accordion" href="#collapse3"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Comments</a></h3>
    </div>
    <div id="collapse3" class="panel-collapse collapse" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <div class="panel-body" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
            {% if Cource.comment_c_set.all %}
                {% for comment_c in Cource.comment_c_set.all %}
                <h3>{{ comment_c.author }} <h6>{{ comment_c.pup_date }}</h6></h3>
                <h4>"{{ comment_c.body }}"</h4>
                {% endfor %}
                {% else %}
                <p> No comments. </p>
                {% endif %}
        </div>
    </div>
</div>

{% endblock %}

project/templates/project/index.html
{% extends 'project/base.html' %}
{% block title %} Students Club Academy {% endblock %}
{% block body %}

<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1"> <span class="glyphicon glyphicon-education" aria-hidden="true"></span> Our Mission</a></h3>
    </div>
        <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">  الإسهام في التعريف بالجامعة من خلال المشاركة الفاعلة في مختلف الأنشطة الثقافية والاجتماعية والرياضية.
        العمل على تقوية التواصل بين الطلاب وإدارة الجامعة بمختلف كلياتها وإداراتها.
        إدارة الأنشطة التي تتبناها عمادة شؤون الطلاب من جهة ترتيبها وتطويرها.
        تنظيم مشاركات الطلاب في الأنشطة بحيث يأخذ كل طالب حقه في المشاركة.
        تعزيز انتماء الطلاب وولائهم لجامعتهم.
        تطوير قدرات الطلاب وخبراتهم في المجالات المختلفة (ثقافياً واجتماعياً ورياضياً وقيادياً ) وتنمية مواهبهم.
        خلق بيئة طلابية فاعلة وجاذبة من ناحية الخدمات والفعاليات المتاحة للطلاب.
        تنمية الوعي الطلابي بالفرص المتاحة بالمدينة الجامعية واندماجهم في الأنشطة الطلابية المشتركة.</div>
    </div>
</div>




<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title" ><a data-toggle="collapse" data-parent="#accordion" href="#collapse3"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> Subjects</a></h3>
    </div>
    <div id="collapse3" class="panel-collapse collapse" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <div class="panel-body" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">

            {% if all_subjects %}
                <ul>
                {% for Subject in all_subjects %}
                    <li><a href="{% url 'project:show_subject' Subject.pk %}" > {{ Subject.name }}</a> ({{ Subject.collage }}) </li></br>
                {% endfor %}
                </ul>
                {% else %}
                    <p> No subjects are available yet. </p>
            {% endif %}

        </div>
    </div>
</div>

{% endblock %}

project/templates/project/subject.html
{% extends 'project/base.html' %}
{% block title %} {{ Subject.name }} {% endblock %}
{% block body %}

<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1"> <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> {{ Subject.name }} </a></h3>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
            <h2> {{ Subject.collage }} - Level: {{ Subject.level }}</h2>
        </div>
    </div>
</div>

<div class="panel panel-default" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
    <div class="panel-heading" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <h3 class="panel-title" ><a data-toggle="collapse" data-parent="#accordion" href="#collapse3"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Courses</a></h3>
    </div>
    <div id="collapse3" class="panel-collapse collapse" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
        <div class="panel-body" style="font-family: 'Proxima Nova','Helvetica','Corbel',sans-serif;background-color:#4b5462;">
            {% if Subject.cource_set.all %}
                <ul>
                {% for Cource in Subject.cource_set.all %}
                    <li><a href="{% url 'project:show_cource' Subject.pk Cource.pk %}">{{ Cource.title }}</a></li></br>
                {% endfor %}
                </ul>
            {% else %}
                <p>No cources are available yet.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}